### ISSUE TITLE
Why company they use gitlab instead of github?

### ISSUE THREAD

**Issue by IMthitinat** [oat431/api-tutorial-flask#1]
Why company they use gitlab instead of github?

**Comment by oat431** [comment]
Most company used GitLab because of the code privacy

Gitlab had self-host policy which better than GitHub (that mean company can have their own code repository but base on GitLab) and also if you want to develop a close source software (in-house software, enterprise software the GitLab is better choice than GitHub because of it can have a private CI/CD pipeline that can connect directly to company server

hope that help. :)
